import Head from 'next/head'
import Image from 'next/image'
import styles from 'src/styles/Home.module.css'
import { UserBox } from "src/components/UserBox"
import Link from "next"

export async function getStaticProps() {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/users`
  );
  const dataLists = await res.json();

  return {
    props: {
      dataLists,
    }
  }
}

export default function Home(props: any) {
  const {dataLists} = props;
  console.log({dataLists});

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Data Fetching SSR Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next.js Data Fetching SSR Test</h1>

        <div className={styles.grid}>

          {/* <Link href={/}>
            <a> */}
            <UserBox
              name="Name"
              username="username"
              email="email"
            />
            {/* </a>
          </Link> */}

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

    </div>
  )
}
